name: template
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pyyaml
  - numpy
  - matplotlib
  - gitpython
  - termcolor
  - colorama
  - jupyter
  - linearmodels
  - sentence-transformers
  - r-base
  - r-data.table
  - r-ggplot2
  - r-Rcpp
  - r-fst
  - r-stringr
  - r-zoo
  - r-readr
  - r-bit
  - r-bit64
  - r-R.utils
  - r-R.methodsS3
  - r-R.oo
  - r-future.apply
  - r-reticulate
  - r-stringi
  - r-plyr
  - r-SnowballC
  - r-snakecase
  - r-tidytext
  - r-bdsmatrix
  - r-survival
  - r-rematch
  - r-readxl
  - r-backports
  - r-crayon
  - r-cowplot
  - r-MASS
  - r-peakRAM
  - r-remotes
  - r-broom
  - r-ggforce
  - r-ggplotify
  - r-ggstance
  - r-gridExtra
  - r-lazyeval
  - r-patchwork
  - r-ggtext
  - r-brms

